import { cn } from '@/lib/utils'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { ClerkProvider } from '@clerk/nextjs'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'josh_sass',
  description: 'josh_sass -generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en" className="light">
        <body
          className={cn(
            'grainy min-h-screen font-sans antialiased',
            inter.className
          )}
        >
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
